version: "3.9"
services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build: ./frontend
    #どのディレクトリのdockerfileからimageをビルドするかを指定
    container_name: react-frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/var/www/html/app
    # ホストマシンの(./app)をコンテナ内のディレクトリ（/var/www/html/app） にマウント
    environment:
      - WATCHPACK_POLLING=true
    tty: true