version: "3.9"
services:
  backend:
    build: ./src
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/app
    command: uvicorn main:app --host 0.0.0.0 --reload